spring.application.name=Hospital-Management-Systemcom.example

spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db
spring.datasource.username=root
spring.datasource.password=Nani@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mahaboob_secret_key
jwt.expiration=86400000
